export const puppyQuotes = [
  'Everything is not going to be not okay.',
  'Whelp',
  "You're doing okay. Middle of the road I suppose.",
  'Life, huh? Weird.',
  'You certainly are a person.',
  'Only 30 more years.',
  'Another day, another existential crisis.',
  "You're not the worst.",
  "Keep on keepin' on",
  '...sigh...',
  "You're doing great, sweetie.",
  '🙃',
  '😬',
  '🤷‍♀️',
  '🫠',
  'Never put off until tomorrow what you can do the day after tomorrow.',
  'Every dead body on Mt. Everest was once a highly motivated person, so… maybe calm down.',
  'When life knocks you down, stay there and take a nap.',
  'Your life can’t fall apart if you never had it together.',
  'You’re naturally funny because your life is a joke.',
  'It is never too late to give up.',
  'It may be that the purpose of your life is to serve as a warning for others.',
  'Live slow. Die whenever.',
  'Trying is the first step to failure.',
  'Don’t just be a part of the problem. Be the whole problem.',
  'Remember: this is just the worst day of your life so far...',
  'You will never fail if you never try',
  'Don"t just dream your dreams. Sleep through them',
  'Remember: even if you are unique, you are probably not useful',
  'The glass is not half empty or half full. It is just another glass you have to wash',
  'Could be worse. Could also be significantly better',
  'Just... keep breathing, I guess',
  'You are managing to occupy space. Well done',
  'Surviving, not thriving',
  'You are definitely in the top 8 billion people I know',
  'Hmmmmmm',
  'Another day to aim low and mostly hit the mark. Or not. Whatever',
  '-insert quote here-',
  '🍻',
  '🫥',
  '🤡',
  '💩',
  '^_____^',
  '<@_@>',
  'Optimism never gets you far',
  'When life gives you lemons, throw them at people you hate',
  'Hang in there 😿',
  'The only way to succeed in life is to always feel like a failure ~ Madi 2025',
];
